### ISSUE TITLE
Keybinds - Sugestion

### ISSUE THREAD

**Issue by peter-kl** [donmaiq/mpv-scripts#5]
Hello,
I'm using your playlistmanager, it's awesome!!!
**Susgestion**: do you know or want to do a keyboard shortcuts list? Like using "z" a list of active keybinds appear at right of the mpv.

thanks . good work.

**Comment by jonniek** [comment]
I've been thinking of some interactive menu since there is quite many keybinds. I forget them occasionally myself since I use some of them rather rarely.

I think having a menu like the following could be useful
```
Playlistmanager actions

○ sort playlist alphanumerically
● sort playlist alphabetically
○ reverse playlist
○ save playlist
○ load playlist
○ shuffle playlist
```

Having this menu could also help reduce the amount of settings people need to fiddle with.

**Comment by jonniek** [comment]
Moved to playlistmanager repository.
